/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        int[] arr1 = {5, 3, 8, 2, 1, 4};
        int[] arr2 = arr1.clone();

        // Sort using Arrays.sort
        java.util.Arrays.sort(arr1);

        // Sort using App.mergeSort
        App.mergeSort(arr2);

        // Check if both arrays are equal after sorting
        assertArrayEquals(arr1, arr2, "Both sorting methods should produce the same result");
    }
}
